### PR TITLE
Metalink improvements

### PR DESCRIPTION
**Pull request by woju**
- restructure the code as python package
- measurement tool for mirrors
- `<mm0:alternates>` (not plugged to machinery) for optimal bandwidth usage, sacrificing freshness

This is based off #5.

### CODE REVIEW

**Comment by woju** [comment]
@marmarek

**Comment by marmarek** [comment]
> restructure the code as python package

Can you not do this? Or if this is really such a big project, separate it from a repository with actual yum repo metadata, and add appropriate handling in repo handling scripts, especially [here](https://github.com/QubesOS/qubes-linux-yum/blob/master/sync_qubes-os.org_repo.sh#L23).

**Comment by woju** [comment]
Not a big project, but big enough that pylint started to be useful and there was some code duplication around mirrors.list loading which I didn't like.

I don't understand the script you linked (nor the general idea underlying all those `update_repo*` scripts), but it looks like adding `qubesmirror/` to the rsync line would work. Or I can provide setup.py and you'd have to install the egg/rpm/whatever on the server.

**Comment by woju** [comment]
And alternatively I could wind it all back to single file, with the command line interface split into subparsers. This would violate "do one thing, and do it well".

**Comment by marmarek** [comment]
> I don't understand the script you linked (nor the general idea underlying all those update_repo* scripts), but it looks like adding qubesmirror/ to the rsync line would work. Or I can provide setup.py and you'd have to install the egg/rpm/whatever on the server.

A high level overview of update repo workflow (for Fedora):
 - `make update-repo-*` copies packages into appropriate directory (`update-repo` target in `builder-fedora/Makefile.builder`)
 - appropriate `update_repo-*` script is called as a sanity check (verify if all packages are signed, etc)
 - (if `AUTOMATIC_UPLOAD=1`) appropriate `sync_*` is called, which uploads packages and needed scripts to the server and calls `update_repo-*` script there to actually regenerate metadata

So, if you can make the script working after just rsync-ing it, then ok. I'd prefer to have as least dependencies there (and assumptions about the environment) as possible.

**Comment by woju** [comment]
Syncing that script does not sound smart. I understand you have to generate repo metadata server-side not to have to have all packages locally (which together are heavy). Is that correct? If so, I'd suggest installing this python code server-side _once_ and then just using it, failing as appropriate if there is no such command. I'd look at it as another thing to install on mirror master, just like rsyncd.

**Comment by woju** [comment]
Also if we'd like to use that lag measurement, I'd say the proper place is from mirror master, so that'd have to be installed anyway.

**Comment by marmarek** [comment]
> Is that correct?

Yes, exactly.

>  If so, I'd suggest installing this python code server-side once and then just using it, failing as appropriate if there is no such command. I'd look at it as another thing to install on mirror master, just like rsyncd.

And remember to update it each time metalink format (or whatever) needs some adjustments? I'd like to keep repository maintenance as automated as possible, the less thing to do manually here the better.
Anyway, if that would be something to be installed on mirror master once, then there are even less reasons to have it in this repository.

**Comment by woju** [comment]
> Anyway, if that would be something to be installed on mirror master once, then there are even less reasons to have it in this repository.

Fine for me. Which repo would you like to have it in?

**Comment by marmarek** [comment]
> Fine for me. Which repo would you like to have it in?

A new one? qubes-mirrors-infrastructure?

**Comment by woju** [comment]
Maybe `qubes-infra-mirror` to have future `qubes-infra-*` repos sort together?

**Comment by marmarek** [comment]
We already have https://github.com/QubesOS/qubes-infrastructure/. qubes-infrastructure-mirrors?

**Review by marmarek — APPROVED** [review]
Besides putting it into separate repo, looks good.
I haven't tested it, but I assume you did.

**Pull request merged**
